---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      become: true
      package:
        name: which
        state: present

    - name: Check whether sl installed
      command: which sl
      register: SL_INSTALLED
      changed_when: false

    - name: Check OS version
      command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure sl is installed
      debug:
        var: SL_INSTALLED

    - name: Show OS version
      debug:
        var: OS_VERSION
