---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      package:
        name: which

    - name: Check whether sl installed
      command: which sl
      environment:
        TERM: xterm
      register: SL_INSTALLED
      changed_when: false

    - debug:
        var: SL_INSTALLED
