---
name: ansible-playbook
on: [deployment, push]

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image: [centos7-latest, centos8-latest]
    steps:
      - name: Upgrade Ansible
        run: |
          pip install --upgrade ansible==2.9.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker | run containers
        run: |
          docker run -d -t --name=${{ matrix.docker-image }} \
          tomonorimatsumura/ansible-test:${{ matrix.docker-image }}

      - name: Install Ansible galaxy roles
        run: |
          ansible-galaxy install -r tests/roles/requirements.yml -p tests/roles

      - name: Execute ansible-playbook command
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i "${{ matrix.docker-image }}," \
          -c docker -u ansible tests/test.yml

      - name: Check idempotency
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          ansible-playbook -i "${{ matrix.docker-image }}," \
          -c docker -u ansible tests/test.yml

      - name: Check if sl command works
        run: |
          docker exec --tty ${{ matrix.docker-image }} env TERM=xterm sl

      - name: Show Ansible version
        run: |
          ansible --version

      - name: Show OS information
        run: |
          docker exec --tty ${{ matrix.docker-image }} env TERM=xterm \
          cat /etc/redhat-release
